version: "3.9"
services:
  expressapp:
    container_name: expressapp
    build: ./backend
    environment:
      - MONGO_URI=mongodb://mongodb:27017/hugadmin-database?retryWrites=true&w=majority
    ports:
      - 4000:4000
    volumes:
      - ./backend:/usr/src/app
    links:
      - mongodb
  mongodb:
    container_name: mongodatabase
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
  reactapp:
    container_name: reactapp
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/app
  nginx:
    build: ./nginx
    ports:
      - 80:80
    links:
      - expressapp
      - reactapp
      - mongodb
    #   - nginx-proxy
    #   - letsencrypt
    # environment:
    #   - VIRTUAL_HOST=143.110.237.52,www.143.110.237.52
    #   - LETSENCRYPT_HOST=143.110.237.52,www.143.110.237.52
    restart: always
#   nginx-proxy:
#     image: jwilder/nginx-proxy
#     restart: always
#     ports:
#       - "80:80"
#       - "443:443"
#     volumes:
#       - /var/run/docker.sock:/tmp/docker.sock:ro
#       - certs:/etc/nginx/certs:ro
#       - vhostd:/etc/nginx/vhost.d
#       - html:/usr/share/nginx/html
#     labels:
#       - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

#   letsencrypt:
#     image: jrcs/letsencrypt-nginx-proxy-companion
#     restart: always
#     environment:
#       - NGINX_PROXY_CONTAINER=nginx-proxy
#     volumes:
#       - certs:/etc/nginx/certs:rw
#       - /var/run/docker.sock:/var/run/docker.sock:ro
#       - vhostd:/etc/nginx/vhost.d
#       - html:/usr/share/nginx/html
# volumes:
#   certs:
#   html:
#   vhostd:
