version: "3.9"
services:
  expressapp:
    container_name: expressapp
    build: ./backend
    environment:
      - MONGO_URI=mongodb://mongodb:27017/hugadmin-database?retryWrites=true&w=majority
    expose:
      - 4000
    volumes:
      - ./backend:/usr/src/app
    links:
      - mongodb
  mongodb:
    container_name: mongodatabase
    image: mongo
    ports:
      - 27018:27017
    volumes:
      - ~/apps/mongo:/data/db
  reactapp:
    container_name: reactapp
    build: ./frontend
    expose:
      - 3000
    volumes:
      - ./frontend:/usr/src/app
  nginx:
    build: ./nginx
    ports:
      - 8080:80
    links:
      - expressapp
      - reactapp
      - mongodb
    restart: always
